# Generated by Django 5.2.17 on 2026-08-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Retail Shop', max_length=150)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=30)),
                ('default_gst', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('voice_billing', models.BooleanField(default=False)),
                ('auto_save_invoices', models.BooleanField(default=True)),
                ('appearance', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
