# Generated by Django 5.2.17 on 2026-08-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='invoice_template',
            field=models.CharField(choices=[('classic', 'Classic Template'), ('modern', 'Modern Template')], default='classic', max_length=30),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
    ]
